-- SEED TEARDOWN — generated by scripts/generate-seed.ts
-- Deletes the seed account and every row attributed to it. Run this before
-- a pilot: demo barangays carrying invented flood reports in a database real
-- residents are using is not a cosmetic problem.

delete from public.pin_votes where pin_id in ('00000000-0000-4000-8000-0000dead0001', '00000000-0000-4000-8000-0000dead0002');
delete from public.pin_votes where voter_id = '00000000-0000-4000-8000-00000000dead';
delete from public.community_pins where id in ('00000000-0000-4000-8000-0000dead0001', '00000000-0000-4000-8000-0000dead0002');
delete from public.profiles where id = '00000000-0000-4000-8000-00000000dead';
delete from auth.users where id = '00000000-0000-4000-8000-00000000dead';
