import { writeFileSync } from "node:fs";
import { MOCK_ZONES, MOCK_POIS, MOCK_HAZARD_SUSCEPTIBILITY } from "../src/lib/mock-data";

/** Postgres string literal. Doubling the apostrophe is the whole escape. */
export function quote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function json(value: unknown): string {
  return `${quote(JSON.stringify(value))}::jsonb`;
}

export function buildSeedSql(): string {
  const lines: string[] = ["-- weatherwell-seed — generated by scripts/generate-seed.ts", ""];

  // Zones first: everything else references them. downstream_zone_id is set in a
  // second pass so the insert order cannot violate the self-reference.
  for (const z of MOCK_ZONES) {
    lines.push(
      `insert into public.zones (id, psgc_barangay_code, name, evacuation_route_text,` +
        ` lat, lng, evacuation_route_path, hotline_number) values (` +
        `${quote(z.id)}, ${quote(z.psgcBarangayCode)}, ${quote(z.name)},` +
        ` ${json(z.evacuationRouteText)}, ${z.lat}, ${z.lng},` +
        ` ${json(z.evacuationRoutePath)}, ${quote(z.hotlineNumber)})` +
        ` on conflict (id) do update set name = excluded.name,` +
        ` evacuation_route_text = excluded.evacuation_route_text,` +
        ` evacuation_route_path = excluded.evacuation_route_path;`
    );
  }
  for (const z of MOCK_ZONES) {
    if (z.downstreamZoneId) {
      lines.push(
        `update public.zones set downstream_zone_id = ${quote(z.downstreamZoneId)}` +
          ` where id = ${quote(z.id)};`
      );
    }
  }

  for (const z of MOCK_ZONES) {
    lines.push(
      `insert into public.evacuation_centers (id, zone_id, name, lat, lng, capacity, status)` +
        ` values (${quote(`center-${z.id}`)}, ${quote(z.id)}, ${quote(z.evacuationCenterName)},` +
        ` ${z.evacuationCenterLat}, ${z.evacuationCenterLng}, ${z.evacuationCenterCapacity},` +
        ` ${quote(z.centerStatus)})` +
        ` on conflict (id) do update set name = excluded.name,` +
        ` capacity = excluded.capacity, status = excluded.status;`
    );
  }

  for (const p of MOCK_POIS) {
    lines.push(
      `insert into public.points_of_interest (id, zone_id, category, name, lat, lng) values (` +
        `${quote(p.id)}, ${quote(p.zoneId)}, ${quote(p.category)}, ${quote(p.name)},` +
        ` ${p.lat}, ${p.lng}) on conflict (id) do update set name = excluded.name;`
    );
  }

  for (const [zoneId, byType] of Object.entries(MOCK_HAZARD_SUSCEPTIBILITY)) {
    for (const [hazardType, riskLevel] of Object.entries(byType)) {
      lines.push(
        `insert into public.hazard_susceptibility (id, zone_id, hazard_type, risk_level) values (` +
          `${quote(`${zoneId}-${hazardType}`)}, ${quote(zoneId)}, ${quote(hazardType)},` +
          ` ${quote(riskLevel)}) on conflict (id) do update set risk_level = excluded.risk_level;`
      );
    }
  }

  return lines.join("\n") + "\n";
}

// Only write the file when run directly, so importing this in a test is side-effect free.
if (process.argv[1]?.endsWith("generate-seed.ts")) {
  writeFileSync("supabase/seed/seed.sql", buildSeedSql());
}
