"use server";

import { PIN_STATUS_ORDER, type PinStatusTag, type PinRemovalReason } from "@/lib/community-pin";
import { createSupabaseUserClient } from "@/lib/supabase/user-server";
import type { ActionResult } from "./action-result";

/**
 * A caption is one line a resident types on a phone while standing in water.
 * The cap is a validation rule, not a storage limit: past a couple of
 * sentences the popup stops being scannable on a small screen, and a caption
 * long enough to be a paragraph is a caller constructing requests by hand.
 */
const CAPTION_MAX_LENGTH = 280;

/** Postgres SQLSTATEs the outbox must not keep retrying. */
const UNIQUE_VIOLATION = "23505";
const INSUFFICIENT_PRIVILEGE = "42501";
const CHECK_VIOLATION = "23514";
const FOREIGN_KEY_VIOLATION = "23503";

/**
 * TRANSIENT, deliberately — the same argument submit-water-level-report.ts
 * makes and for the same reason. The three permanent codes below are
 * structurally permanent: an RLS denial, a CHECK violation and a bad FK cannot
 * become true later. The absence of a session is the opposite. A blocked or
 * chunked `sb-` cookie, a refresh token that expired while the device was
 * offline for days, a cookie stripped in transit — every one resolves on a
 * later attempt, and every one is likeliest during exactly the bad
 * connectivity the outbox exists for.
 *
 * Calling it permanent would make drainOutbox skip the entry forever AND
 * mergePins drop the pin off the map, so a resident who watched their pin
 * appear would lose it silently and irrecoverably.
 */
const NO_SESSION: ActionResult = {
  ok: false,
  permanent: false,
  error: "No session yet — cannot attribute this pin write. Will retry.",
};

/**
 * Zero rows and no error is what an UPDATE refused by RLS looks like from
 * postgrest — there is no error to inspect, only an empty result. Treating
 * that as success is how the outbox marks a refused edit delivered and drops
 * it, so every update in this file asks for the affected rows and routes an
 * empty answer here.
 *
 * Permanent: the row is either someone else's or gone, and neither changes
 * on a retry.
 */
function refused(what: string): ActionResult {
  return { ok: false, permanent: true, error: `That pin is not yours to ${what}, or no longer exists.` };
}

function classify(error: { code?: string; message?: string }): ActionResult {
  const permanent =
    error.code === INSUFFICIENT_PRIVILEGE ||
    error.code === CHECK_VIOLATION ||
    error.code === FOREIGN_KEY_VIOLATION;
  return { ok: false, permanent, error: error.message ?? `Database error ${error.code ?? "(no code)"}` };
}

/**
 * Validation failures are permanent by definition: a rejection of the input
 * itself cannot become valid by being sent again. Returning the trimmed
 * caption on success keeps the one call site from trimming twice and storing
 * the untrimmed copy.
 */
function validateCaption(caption: string): { ok: true; caption: string } | { ok: false; result: ActionResult } {
  const trimmed = caption.trim();
  if (trimmed.length === 0) {
    return { ok: false, result: { ok: false, permanent: true, error: "A pin needs a caption." } };
  }
  if (trimmed.length > CAPTION_MAX_LENGTH) {
    return {
      ok: false,
      result: {
        ok: false,
        permanent: true,
        error: `Caption is ${trimmed.length} characters; the limit is ${CAPTION_MAX_LENGTH}.`,
      },
    };
  }
  return { ok: true, caption: trimmed };
}

function validateStatusTag(statusTag: PinStatusTag): ActionResult | null {
  return PIN_STATUS_ORDER.includes(statusTag)
    ? null
    : { ok: false, permanent: true, error: `Unknown pin status tag: ${statusTag}` };
}

/**
 * getClaims, never getSession: it verifies the JWT signature against the
 * project's published keys. getSession does not revalidate and a spoofed
 * cookie would pass it.
 */
async function callerId(
  supabase: Awaited<ReturnType<typeof createSupabaseUserClient>>
): Promise<string | undefined> {
  const { data } = await supabase.auth.getClaims();
  return data?.claims?.sub;
}

export interface CreatePinInput {
  /** Generated by the outbox. Becomes the row's primary key, so replay is idempotent. */
  id: string;
  zoneId: string;
  statusTag: PinStatusTag;
  caption: string;
  lat: number;
  lng: number;
}

/**
 * Files a resident's map pin.
 *
 * Every write goes through a Server Action rather than straight from the
 * browser, so validation runs where a client cannot bypass it. RLS is the
 * backstop underneath: `pins_insert_own` refuses any row whose author_id is
 * not the caller's own uid.
 */
export async function createPin(input: CreatePinInput): Promise<ActionResult> {
  const caption = validateCaption(input.caption);
  if (!caption.ok) return caption.result;
  const badTag = validateStatusTag(input.statusTag);
  if (badTag) return badTag;

  const supabase = await createSupabaseUserClient();
  const userId = await callerId(supabase);
  if (!userId) return NO_SESSION;

  // Exactly the columns that are still insertable. photo_path, created_at,
  // removed and removed_reason were revoked from the resident's grant, so
  // naming any of them raises 42501 — which this file classifies permanent,
  // and a permanent failure on createPin bins the pin.
  const { error } = await supabase.from("community_pins").insert({
    id: input.id,
    zone_id: input.zoneId,
    status_tag: input.statusTag,
    caption: caption.caption,
    lat: input.lat,
    lng: input.lng,
    // The caller's own uid, never one supplied by the client.
    author_id: userId,
  });

  if (!error) return { ok: true };

  // The outbox re-sends anything it did not see confirmed, so a row that
  // already landed under this id is a success, not a failure. (Contrast the
  // votes and check-ins tables, where the primary key is not the outbox's own
  // id and a collision means something else.)
  if (error.code === UNIQUE_VIOLATION) return { ok: true };

  return classify(error);
}

/**
 * A resident correcting their own pin.
 *
 * Filtered by id alone. RLS's `pins_update_own_or_operator` is what scopes
 * this to the author (or an operator fixing an obvious mistake); repeating
 * that as an author_id filter here would be a second copy of the same rule in
 * a second language, and two copies drift.
 */
export async function editPin(input: {
  pinId: string;
  statusTag: PinStatusTag;
  caption: string;
}): Promise<ActionResult> {
  const caption = validateCaption(input.caption);
  if (!caption.ok) return caption.result;
  const badTag = validateStatusTag(input.statusTag);
  if (badTag) return badTag;

  const supabase = await createSupabaseUserClient();
  // Checked before the update, not after: with no uid the policy matches no
  // rows, and the zero-row branch below would bin a perfectly good edit as a
  // permanent refusal.
  if (!(await callerId(supabase))) return NO_SESSION;

  const { data, error } = await supabase
    .from("community_pins")
    .update({ status_tag: input.statusTag, caption: caption.caption })
    .eq("id", input.pinId)
    .select("id");

  if (error) return classify(error);
  if (!data || data.length === 0) return refused("edit");
  return { ok: true };
}

/**
 * The author withdrawing their own pin.
 *
 * A soft delete, not a hard one, and not by preference: DELETE is revoked from
 * every role on every table in this database, so there is no hard delete to
 * choose. The row is retained because it is the only record that the pin ever
 * existed, and the resident's actual intent — it disappears from every map —
 * is satisfied by `removed`.
 *
 * It writes `removed` and NOTHING else. `pins_protect_moderation_columns` is a
 * BEFORE UPDATE trigger that raises 42501 for a non-operator whenever
 * removed_reason changes at all, so stamping a reason here would fail for
 * every resident, be classified permanent, and silently bin the author's own
 * delete.
 *
 * Leaving it NULL is also the honest record. The column's CHECK allows only
 * 'net_score' and 'admin', and neither describes "the author took it down" —
 * both are moderation verdicts, and this is not moderation. So the three
 * states read: no reason = the author withdrew it, 'admin' = an operator
 * removed it, 'net_score' = the neighbours did.
 */
export async function deleteOwnPin(input: { pinId: string }): Promise<ActionResult> {
  const supabase = await createSupabaseUserClient();
  if (!(await callerId(supabase))) return NO_SESSION;

  const { data, error } = await supabase
    .from("community_pins")
    .update({ removed: true })
    .eq("id", input.pinId)
    .select("id");

  if (error) return classify(error);
  if (!data || data.length === 0) return refused("delete");
  return { ok: true };
}

/**
 * The operator path: removing someone else's pin, or restoring one that
 * voting took down wrongly — PRD Core Feature #5's "remove or restore any
 * pin", the same human override the alert pipeline has.
 *
 * Nothing here checks who the caller is. `private.is_operator()` inside the
 * RLS policy and the moderation trigger is the authority, and a role check
 * written here as well would be a second copy free to drift from it. A
 * resident whose client called this gets zero rows or 42501, both permanent.
 */
export async function setPinRemoved(input: {
  pinId: string;
  removed: boolean;
  reason: PinRemovalReason;
}): Promise<ActionResult> {
  const supabase = await createSupabaseUserClient();
  if (!(await callerId(supabase))) return NO_SESSION;

  const { data, error } = await supabase
    .from("community_pins")
    // Cleared on restore: a restored pin carrying the verdict that removed it
    // would show in the moderation panel as still judged.
    .update({ removed: input.removed, removed_reason: input.removed ? input.reason : null })
    .eq("id", input.pinId)
    .select("id");

  if (error) return classify(error);
  if (!data || data.length === 0) return refused("moderate");
  return { ok: true };
}
