"use server";

import { createSupabaseUserClient } from "@/lib/supabase/user-server";
import type { CheckInStatus } from "@/lib/types";
import type { ActionResult } from "./action-result";

/** Postgres SQLSTATEs this action must not keep retrying. */
const INSUFFICIENT_PRIVILEGE = "42501";
const CHECK_VIOLATION = "23514";
const FOREIGN_KEY_VIOLATION = "23503";
const TIME_OUT_OF_RANGE = "22023";

/**
 * TRANSIENT, deliberately — the same argument every other action in this app
 * makes. A blocked or chunked `sb-` cookie, a refresh token that expired
 * while the device was offline for days, a cookie stripped in transit: every
 * one resolves on a later attempt, and every one is likeliest during exactly
 * the bad connectivity the outbox exists for. Calling it permanent would make
 * drainOutbox skip the entry forever AND mergeCheckIns drop the resident's
 * answer off the screen — for the one response in this app that names a
 * person and says whether they need help.
 */
const NO_SESSION: ActionResult = {
  ok: false,
  permanent: false,
  error: "No session yet — cannot attribute this check-in. Will retry.",
};

/**
 * getClaims, never getSession: it verifies the JWT signature against the
 * project's published keys. getSession does not revalidate and a spoofed
 * cookie would pass it.
 */
async function callerId(
  supabase: Awaited<ReturnType<typeof createSupabaseUserClient>>
): Promise<string | undefined> {
  const { data } = await supabase.auth.getClaims();
  return data?.claims?.sub;
}

/**
 * `42501` (RLS denial), `23514` (a status the CHECK constraint rejects — this
 * action already validates that before the database is even touched, so this
 * is belt-and-braces) and `23503` (the zone does not exist) are all
 * structurally permanent: none of them becomes true on a retry.
 *
 * Deliberately NOT special-cased here: `23505`, unique violation. createPin
 * treats it as success because a replayed insert under the same id is the
 * same row. This table is unique on `(zone_id, user_id)`, not on the id the
 * outbox generates, so a collision here is never a replay — it is a genuine
 * second write, a resident's answer changing from "safe" to "needs_help" —
 * and reporting it as success would silently discard the most consequential
 * message in the app. The upsert below, targeting that exact conflict pair,
 * is what should absorb a same-answer replay before Postgres ever raises
 * 23505; if one somehow still surfaces, falling through to the default below
 * classifies it transient (not one of the three permanent codes) rather than
 * success or a permanent drop, so the outbox retries instead of either lying
 * or giving up.
 */
function classify(error: { code?: string; message?: string }): ActionResult {
  // private.honest_check_in_time() refuses a check-in claiming to be more
  // than 3 days old (ruling R3). Retrying cannot make it younger, so it is
  // permanent — but deliberately WITHOUT reason "too_old", whose badge copy
  // tells the resident to report the flood again. That sentence is about
  // water-level reports, not check-ins.
  if (error.code === TIME_OUT_OF_RANGE) {
    return { ok: false, permanent: true, error: error.message ?? "check-in too old" };
  }
  const permanent =
    error.code === INSUFFICIENT_PRIVILEGE ||
    error.code === CHECK_VIOLATION ||
    error.code === FOREIGN_KEY_VIOLATION;
  return { ok: false, permanent, error: error.message ?? `Database error ${error.code ?? "(no code)"}` };
}

export interface RecordCheckInInput {
  /** Generated by the outbox. Becomes the row's primary key, so replay is idempotent — see the upsert below for why the conflict target is not this id. */
  id: string;
  zoneId: string;
  status: CheckInStatus;
  /**
   * ISO timestamp of when the resident actually checked in, carried through
   * by the outbox for a write sent later than it was made. Already on the
   * server's clock: /api/outbox derives it from how long ago the device
   * queued the write, never from the device's own absolute time. Omitted for an
   * ordinary, non-queued check-in, so the column keeps its database-clock
   * default. private.honest_check_in_time() (see
   * supabase/migrations/20260915103000_honest_write_times.sql) is what
   * actually enforces honesty server-side: it clamps a future time to now()
   * and, on the upsert conflict path below, never lets an older write
   * regress a newer one already stored.
   */
  madeAt?: string;
}

/**
 * Records (or replaces) a resident's check-in for a zone.
 *
 * A check-in names a person and says whether they need help — the one
 * response in this app that must never be cached (see the route handler and
 * `public/sw.js`'s dedicated branch) and the one write in this file's family
 * where treating a duplicate as success would be wrong (see `classify`
 * above).
 *
 * **Upserts, does not insert.** The table is unique on `(zone_id, user_id)`
 * and a resident is explicitly allowed to change their answer — a second
 * write from the same resident for the same zone is a legitimate change of
 * answer, not a duplicate. `onConflict: "zone_id,user_id"` is required, not
 * decorative: that is the shape PostgREST's `Prefer: merge-duplicates`
 * actually emits for this payload (every column, not just the one that
 * changed), matching exactly what is grantable on both INSERT and UPDATE —
 * `(id, zone_id, user_id, status)` — with `id` included on purpose so a
 * second queued write for the same zone converges the row onto its own id
 * rather than being refused for naming a column it cannot touch.
 */
export async function recordCheckIn(input: RecordCheckInInput): Promise<ActionResult> {
  if (input.status !== "safe" && input.status !== "needs_help") {
    return { ok: false, permanent: true, error: `Unknown check-in status: ${input.status}` };
  }

  const supabase = await createSupabaseUserClient();
  const userId = await callerId(supabase);
  if (!userId) return NO_SESSION;

  const { error } = await supabase.from("evacuation_check_ins").upsert(
    {
      id: input.id,
      zone_id: input.zoneId,
      // The caller's own uid, verified, never one supplied by the client —
      // checkins_insert_own and checkins_update_own enforce this too, but a
      // client that never even sends a foreign user_id is one fewer thing
      // RLS has to catch.
      user_id: userId,
      status: input.status,
      // Only sent when the outbox is replaying a write made earlier — an
      // ordinary check-in omits the key entirely and keeps the column's
      // database-clock default.
      ...(input.madeAt ? { checked_in_at: input.madeAt } : {}),
    },
    { onConflict: "zone_id,user_id" }
  );

  if (!error) return { ok: true };

  return classify(error);
}
