"use server";

import { DEPTH_LEVELS, type DepthLevel } from "@/lib/depth";
import { after } from "next/server";
import { createSupabaseUserClient } from "@/lib/supabase/user-server";
import { runThresholdCheck } from "@/lib/threshold-check";
import type { ActionResult } from "./action-result";

export interface SubmitReportInput {
  /** Generated by the outbox. Becomes the row's primary key, so replay is idempotent. */
  id: string;
  zoneId: string;
  depthLevel: DepthLevel;
  /** The device's position when the report was filed. Omitted when unavailable — never blocks the write. See the geofence trigger (20260922094703_report_geofence_and_rate_limit.sql) for why. */
  lat?: number;
  lng?: number;
  /**
   * ISO timestamp of when the resident actually made this report, carried
   * through by the outbox for a write sent later than it was made. Already on
   * the server's clock: /api/outbox derives it from how long ago the device
   * queued the write, never from the device's own absolute time. Omitted
   * for an ordinary, non-queued submission, so the column keeps its
   * database-clock default. private.honest_report_time() (see
   * supabase/migrations/20260915143824_honest_write_times.sql) is what
   * actually enforces honesty on the server side: it clamps a future time to
   * now() and refuses one more than 6 hours old.
   */
  madeAt?: string;
}

/** Postgres SQLSTATEs the outbox must not keep retrying. */
const UNIQUE_VIOLATION = "23505";
const INSUFFICIENT_PRIVILEGE = "42501";
const CHECK_VIOLATION = "23514";
const FOREIGN_KEY_VIOLATION = "23503";
/** private.honest_report_time() raises this for a report more than 6 hours old. */
const REPORT_TOO_OLD = "22023";
/** private.enforce_report_geofence_and_rate_limit()'s two refusals, in its own words. */
const TOO_FAR = /too far from the zone/i;
const RATE_LIMITED = /too many reports for this zone/i;

/**
 * Files a resident's water-level report.
 *
 * Every write goes through a Server Action rather than straight from the
 * browser, so validation runs where a client cannot bypass it. Stage 3's
 * geofence and rate limit slot in here, and RLS is the backstop underneath.
 */
export async function submitWaterLevelReport(
  input: SubmitReportInput
): Promise<ActionResult> {
  if (!DEPTH_LEVELS.includes(input.depthLevel)) {
    return { ok: false, permanent: true, error: `Unknown depth level: ${input.depthLevel}` };
  }

  const supabase = await createSupabaseUserClient();

  // getClaims, never getSession: it verifies the JWT signature against the
  // project's published keys. getSession does not revalidate and a spoofed
  // cookie would pass it.
  const { data } = await supabase.auth.getClaims();
  const userId = data?.claims?.sub;
  if (!userId) {
    // TRANSIENT, deliberately — and it is the one classification in this file
    // that has to be argued for. The other three permanent codes are
    // structurally permanent: an RLS denial, a CHECK violation and a bad FK
    // cannot become true later. The absence of a session is the opposite. A
    // blocked or chunked `sb-` cookie, a refresh token that expired while the
    // device was offline for days, a cookie stripped in transit — every one of
    // those resolves on a later attempt, and every one of them is most likely
    // to happen during exactly the bad connectivity the outbox exists for.
    //
    // Calling it permanent would make drainOutbox skip the entry forever AND
    // mergeReports drop it from the screen, so a resident already told "Report
    // recorded" would lose the report silently and irrecoverably — the precise
    // failure this whole write path was built to prevent.
    return {
      ok: false,
      permanent: false,
      error: "No session yet — cannot attribute this report. Will retry.",
    };
  }

  const { error } = await supabase.from("water_level_reports").insert({
    id: input.id,
    zone_id: input.zoneId,
    depth_level: input.depthLevel,
    // The caller's own uid, never one supplied by the client. RLS enforces
    // this too; doing it here means we never even ask.
    reporter_id: userId,
    // Only sent when the outbox is replaying a write made earlier — an
    // ordinary submission omits the key entirely and keeps the column's
    // database-clock default.
    ...(input.madeAt ? { reported_at: input.madeAt } : {}),
    // Omitted entirely (not null) when the device had no position, so the
    // insert's column list matches whichever grant applies either way.
    ...(input.lat !== undefined && input.lng !== undefined ? { lat: input.lat, lng: input.lng } : {}),
  });

  if (!error) {
    // Evaluate the crowd-report threshold now, after the response is sent,
    // rather than at the next scheduled run (every 3 hours at best).
    after(async () => {
      const check = await runThresholdCheck();
      if (!check.ok) console.error(`threshold check after report failed: ${check.error}`);
    });
    return { ok: true };
  }

  // The outbox re-sends anything it did not see confirmed, so a row that
  // already landed is a success, not a failure.
  if (error.code === UNIQUE_VIOLATION) return { ok: true };

  // Checked before the general classification below: a report more than 6
  // hours old can never succeed on retry, so this must be permanent, and the
  // outbox needs the specific reason to drop the entry rather than keep it
  // queued indefinitely.
  if (error.code === REPORT_TOO_OLD) {
    return { ok: false, permanent: true, reason: "too_old", error: error.message };
  }

  // Named, so the phone can say why instead of "This couldn't be accepted".
  // A position outside the barangay never passes on retry...
  if (error.code === CHECK_VIOLATION && TOO_FAR.test(error.message)) {
    return { ok: false, permanent: true, reason: "too_far", error: error.message };
  }
  // ...but one report per barangay every 5 minutes does, once the window passes.
  if (RATE_LIMITED.test(error.message)) {
    return { ok: false, permanent: false, reason: "rate_limited", error: error.message };
  }

  const permanent =
    error.code === INSUFFICIENT_PRIVILEGE ||
    error.code === CHECK_VIOLATION ||
    error.code === FOREIGN_KEY_VIOLATION;

  return { ok: false, permanent, error: error.message };
}
